/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Appointments
 #	author : miyako
 #	2017/04/03
 #
 # --------------------------------------------------------------------------------*/

#import <CalendarStore/CalendarStore.h>
#import "libjson.h"
#include "sqlite3.h"

// --- Appointments
void ALL_APPOINTMENTS(sLONG_PTR *pResult, PackagePtr pParams);
void Get_appointment(sLONG_PTR *pResult, PackagePtr pParams);
void UPDATE_APPOINTMENT(sLONG_PTR *pResult, PackagePtr pParams);
void DELETE_APPOINTMENT(sLONG_PTR *pResult, PackagePtr pParams);
void ON_APPOINTMENT_CALL(sLONG_PTR *pResult, PackagePtr pParams);
void CREATE_APPOINTMENT(sLONG_PTR *pResult, PackagePtr pParams);
void APPOINTMENT_NAMES(sLONG_PTR *pResult, PackagePtr pParams);

void json_wconv(C_TEXT &t, std::wstring &u32);
void json_stringify(JSONNODE *json, C_TEXT &t, BOOL pretty);
JSONNODE *json_parse(C_TEXT &t);

void json_set_event(JSONNODE *obj, CalEvent *event);

void json_set_text(JSONNODE *n, const wchar_t *name, NSString *value);


NSString *json_get_text(JSONNODE *obj, const wchar_t *name);
NSURL *json_get_url(JSONNODE *obj, const wchar_t *name);
NSDate *json_get_date(JSONNODE *obj, const wchar_t *name);

void event_to_json(CUTF16String *eventId, CUTF16String *eventJson);

CalCalendarStore *json_get_calendar_store(JSONNODE *obj);
CalEvent *json_get_event(JSONNODE *obj, C_TEXT& Param1);
CalCalendar *json_get_calendar(JSONNODE *obj, C_TEXT& Param1);


void listenerInit(void);
void listenerLoop(void);
void listenerLoopStart(void);
void listenerLoopFinish(void);
void listenerLoopExecute(void);
void listenerLoopExecuteMethod(void);

typedef PA_long32 process_number_t;
typedef PA_long32 process_stack_size_t;
typedef PA_long32 method_id_t;
typedef PA_Unichar* process_name_t;

void onStartup();
void onCloseProcess();
bool isProcessOnExit();

typedef enum
{
	
	notification_create = 0,
	notification_update = 1,
	notification_delete = 2
	
} notification_t;
